### PR TITLE
Proposing five new rules to enforce

### PR DESCRIPTION
**Pull request by harkshark**
### What
This PR proposes the enforcement of five ESLint rules.

### Why
Linting will hopefully make our code easier to read, easier to maintain, and less prone to errors. But some rules can be more of a burden than actually helpful. Let's decide as a team what we want to enforce.

### Test Coverage
Linting is a form of testing.

### Risks and Deploy Considerations
Now that our linting config is shared across repos, we'll need to make sure to fix all the things in all the places. I have a branch to fix Jabiru and then I'll run it through Shrike and Admin Panel.

I'm not sure of the order of operations here, once approved. Maybe fix the things in the external repos and then merge this in?

### CODE REVIEW

**Comment by sdpeyton** [comment]
here are my thoughts:
- `no-else-return`: I used to be against this one, but my thoughts on it have shifted to indifference. I will say that the consistency of enforcing this rule would be nice.
- `no-console`: I'm against this one, not because I think its a bad rule to enforce in production, but because this would make debugging difficult. I occasionally log things because I find it easier to debug than breakpoints for certain circumstances (not sure about everyone else though). I'm not sure how much of an issue stray console logs have been in the past so I'm concerned about the costs potentially outweighing the benefits.
- `no-unused-vars`: :+1: 
- `react/jsx-boolean-value`: I actually would prefer the `"never"` option for this if we were to specify one way of the other, because we have many examples of optional parameters that would seem cumbersome to have to specify, and may add additional confusion. For instance, the button option would have to be:
```jsx
  <Button buttonStyle="primary" outline={false} disabled={false}>Click Me!</Button>
```
- `react/no-unused-prop-type`: :+1:

**Comment by jakelear** [comment]
I left a comment on the issue I think, but for `no-console` - is it possible to set this to "Warn." I'm with @sdpeyton that it makes debugging a pain in the ass if you can't console.log, but I agree that we don't want them in production. I'm good with the rest of them.

**Comment by harkshark** [comment]
@jakelear I'm sure there's a way to configure `no-console` to warn. I'll investigate!

**Comment by harkshark** [comment]
@sdpeyton, @jakelear I've configured `no-console` to warn, not error. This will catch any forgotten `console.log` methods and if it's an intentional insertion we can ignore it with `// eslint-disable-line no-console`.

**Comment by sdpeyton** [comment]
@harkshark nice! ya i'm happy with that rule if its set to "warn". I also wonder if @jakelear 's new jabiru PR helps with some of those debugging issues and maybe we can set it back to error now.

**Pull request merged**
